remote_theme: mmistakes/minimal-mistakes

title: "markusgrotz.com"
name: "Markus Grotz"
url: "https://markusgrotz.github.io"
teaser: "/assets/images/teaser.jpg"

author:
  name: "Markus Grotz"
  avatar: "/assets/images/markus.jpg"
  bio: "Markus is a Postdoctoral Scholar with Dieter Fox and the research project Robotic Manipulation in Densely Packed Containers"
  location: "Seattle, USA"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:Markus Grotz <family_name> <at> uw <dot> edu"

    - label: "Project Website"
      icon: "fas fa-fw fa-link"
      url: "https://robotic-manipulation.sciencehub.uw.edu"

    - label: "RSELab Website"
      icon: "fas fa-fw fa-link"
      url: "https://rse-lab.cs.washington.edu/people/"

    - label: "H2T Website"
      icon: "fas fa-fw fa-link"
      url: "https://h2t.anthropomatik.kit.edu/21_918.php"

    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin-in"
      url: "https://www.linkedin.com/in/markus-grotz/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/markusgrotz"
    - label: "GitLab"
      icon: "fab fa-fw fa-gitlab"
      url: "https://gitlab.com/markusgrotz"
    - label: "Google Scholar"
      icon: "fas fa-fw fa-graduation-cap"
      url: "https://scholar.google.com/citations?user=ywTBxOkAAAAJ&hl=de&oi=ao"

footer:
  links:

atom_feed:
  hide: true


encoding: "utf-8"


include:
  - .htaccess
  - _pages



plugins:
  - jekyll-include-cache
  - jekyll-remote-theme
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist


defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

  - scope:
      path: "about"
      type: pages
    values:
      layout: single
      author_profile: true
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

