remote_theme: mmistakes/minimal-mistakes

title: "markusgrotz.com"
name: "Markus Grotz"
url: "https://markusgrotz.github.io"
teaser: "/assets/images/teaser.jpg"

author:
  name: "Markus Grotz"
  avatar: "/assets/images/markus.jpg"
  bio: "Markus is a PostDoc and part of the research team of Professor Tamim Asfour, High Performance Humanoid Technologies Lab (H2T) at the Institute of Anthropomatics and Robotics, Karlsruhe Institute of Technology (KIT)"
  location: "Karlsruhe, Germany"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:Markus Grotz <given_name> <dot> <family_name> <at> kit <dot> edu"
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://h2t.anthropomatik.kit.edu/21_918.php"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin-in"
      url: "https://www.linkedin.com/in/markus-grotz/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/markusgrotz"
    - label: "GitLab"
      icon: "fab fa-fw fa-gitlab"
      url: "https://gitlab.com/markusgrotz"

footer:
  links:

atom_feed:
  hide: true


encoding: "utf-8"


include:
  - .htaccess
  - _pages



plugins:
  - jekyll-include-cache
  - jekyll-remote-theme
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist


defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

